# SPDX-License-Identifier: GPL-3.0+
# Originally Copyright Roger Meier <r.meier@siemens.com>
# Adapted for GRUB by Alexander Graf <agraf@suse.de>
#
# Build GRUB on Travis CI - https://www.travis-ci.org/
#

dist: xenial

language: c

addons:
  apt:
    packages:
    - build-essential
    - libsdl1.2-dev
    - python
    - iasl
    - lzop
    - unifont
    - autopoint

branches:
  only:
    - master

script:
  # Comments must be outside the command strings below, or the Travis parser
  # will get confused.
  - ./bootstrap

  # Build all selected GRUB targets.
  - for target in $GRUB_TARGETS; do
      plat=${target#*-};
      arch=${target%-*};
      echo "Building $target";
      mkdir obj-$target;
      JOBS=`getconf _NPROCESSORS_ONLN 2> /dev/null || echo 1`;
      [ "$JOBS" == 1 ] || JOBS=$(($JOBS + 1));
      ( cd obj-$target && ../configure --target=$arch --with-platform=$plat --prefix=/tmp/grub && make -j$JOBS && make -j$JOBS install ) &> log || ( cat log; false );
    done

matrix:
  include:
  # Each env setting here is a dedicated build.
    - name: "x86_64"
      env:
       - GRUB_TARGETS="x86_64-efi"
  #    - GRUB_TARGETS="x86_64-efi x86_64-xen"
    - name: "i386"
      env:
       - GRUB_TARGETS="i386-coreboot i386-efi i386-pc"
  #    - GRUB_TARGETS="i386-coreboot i386-efi i386-ieee1275 i386-multiboot i386-pc i386-qemu i386-xen i386-xen_pvh"
  # - name: "powerpc"
  #   env:
  #     - GRUB_TARGETS="powerpc-ieee1275"
  #     - CROSS_TARGETS="powerpc64-linux"
  # - name: "sparc64"
  #   env:
  #     - GRUB_TARGETS="sparc64-ieee1275"
  #     - CROSS_TARGETS="sparc64-linux"
  # - name: "ia64"
  #   env:
  #     - GRUB_TARGETS="ia64-efi"
  #     - CROSS_TARGETS="ia64-linux"
  # - name: "mips"
  #   env:
  #     - GRUB_TARGETS="mips-arc mipsel-arc mipsel-qemu_mips mips-qemu_mips"
  #     - CROSS_TARGETS="mips64-linux"
  # - name: "arm"
  #   env:
  #     - GRUB_TARGETS="arm-coreboot arm-efi arm-uboot"
  #     - GRUB_TARGETS="arm-efi"
  #     - CROSS_TARGETS="arm-linux-gnueabi"
  # - name: "arm64"
  #   env:
  #     - GRUB_TARGETS="arm64-efi"
  #     - CROSS_TARGETS="aarch64-linux"
  # - name: "riscv32"
  #   env:
  #     - GRUB_TARGETS="riscv32-efi"
  #     - CROSS_TARGETS="riscv32-linux"
  # - name: "riscv64"
  #   env:
  #     - GRUB_TARGETS="riscv64-efi"
  #     - CROSS_TARGETS="riscv64-linux"
