dist: xenial

language: c

addons:
  apt:
    packages:
    - cppcheck
    - sloccount
    - sparse
    - bc
    - build-essential
    - libsdl1.2-dev
    - python
    - python-virtualenv
    - swig
    - libpython-dev
    - iasl
    - rpm2cpio
    - wget
    - device-tree-compiler
    - lzop
    - liblz4-tool
    - libisl15
    - unifont

script:
  - ./autogen.sh

  - plat=${GRUB_TARGET#*-};
    arch=${GRUB_TARGET%-*};
    echo "Building $GRUB_TARGET";
    
  - ./configure --target=$arch --with-platform=$plat --prefix=/tmp/grub
  - make
  - make install
  - make clean

matrix:
  include:
    - name: "x86_64-efi"
      env:
        - GRUB_TARGET="x86_64-efi"
    - name: "i386-efi"
      env:
        - GRUB_TARGET="i386-efi"
    - name: "i386-pc"
      env:
        - GRUB_TARGET="i386-pc"
