dist: xenial

language: c

addons:
  apt:
    packages:
    - cppcheck
    - sloccount
    - sparse
    - bc
    - build-essential
    - libsdl1.2-dev
    - python
    - python-virtualenv
    - swig
    - libpython-dev
    - iasl
    - rpm2cpio
    - wget
    - device-tree-compiler
    - lzop
    - liblz4-tool
    - libisl15
    - unifont

script:
  - ./autogen.sh

  - for target in $GRUB_TARGETS; do
      plat=${target#*-};
      arch=${target%-*};
      echo "Building $target";
      mkdir obj-$target;
      ( cd obj-$target && ../configure --target=$arch --with-platform=$plat --prefix=/tmp/grub && make && make install ) &> log || ( cat log; false );
    done

matrix:
  include:
    - name: "x86_64"
      env:
        - GRUB_TARGETS="x86_64-efi"
    - name: "i386"
      env:
        - GRUB_TARGETS="i386-efi i386-pc"